CREATE TABLE `tbl_m_items` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `id_satuan` INT(11) NULL DEFAULT '7',
    `id_kategori` INT(11) NULL DEFAULT '0',
    `id_kategori_lab` INT(11) NULL DEFAULT '0',
    `id_kategori_gol` INT(11) NULL DEFAULT '0',
    `id_lokasi` INT(11) NULL DEFAULT '0',
    `id_merk` INT(11) NULL DEFAULT '0',
    `id_user` INT(11) NULL DEFAULT '0',
    `tgl_simpan` DATETIME NULL DEFAULT NULL,
    `tgl_modif` DATETIME NULL DEFAULT NULL,
    `kode` VARCHAR(65) NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
    `barcode` VARCHAR(65) NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
    `item` VARCHAR(160) NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
    `item_alias` TEXT NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
    `item_kand` TEXT NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
    `item_kand2` TEXT NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
    `jml` FLOAT NULL DEFAULT NULL,
    `jml_display` FLOAT NULL DEFAULT '0',
    `jml_limit` FLOAT NULL DEFAULT '0',
    `harga_beli` DECIMAL(10,2) NULL DEFAULT NULL,
    `subtotal` DECIMAL(10,2) NULL DEFAULT '0.00',
    `harga_beli_ppn` DECIMAL(10,2) NULL DEFAULT NULL,
    `harga_jual` DECIMAL(10,2) NULL DEFAULT NULL,
    `harga_hasil` DECIMAL(10,2) NULL DEFAULT NULL,
    `harga_grosir` DECIMAL(10,2) NULL DEFAULT NULL,
    `remun_tipe` ENUM('0','1','2') NULL DEFAULT '0' COLLATE 'utf8mb3_general_ci',
    `remun_perc` DECIMAL(10,2) NULL DEFAULT '0.00',
    `remun_nom` DECIMAL(10,2) NULL DEFAULT '0.00',
    `apres_tipe` ENUM('0','1','2') NULL DEFAULT '0' COLLATE 'utf8mb3_general_ci',
    `apres_perc` DECIMAL(10,2) NULL DEFAULT '0.00',
    `apres_nom` DECIMAL(10,2) UNSIGNED NULL DEFAULT '0.00',
    `status_promo` ENUM('0','1') NULL DEFAULT '0' COLLATE 'utf8mb3_general_ci',
    `status_subt` ENUM('0','1') NULL DEFAULT '0' COLLATE 'utf8mb3_general_ci',
    `status_lab` ENUM('0','1') NULL DEFAULT '0' COLLATE 'utf8mb3_general_ci',
    `status_brg_dep` ENUM('0','1') NULL DEFAULT '0' COLLATE 'utf8mb3_general_ci',
    `status_stok` ENUM('0','1') NULL DEFAULT '0' COLLATE 'utf8mb3_general_ci',
    `status_racikan` ENUM('0','1') NULL DEFAULT '0' COLLATE 'utf8mb3_general_ci',
    `status_etiket` ENUM('0','1','2') NULL DEFAULT '0' COMMENT '0=netral;1=etiket putih;2=etiket biru;' COLLATE 'utf8mb3_general_ci',
    `status_hps` ENUM('0','1') NULL DEFAULT '0' COLLATE 'utf8mb3_general_ci',
    `sl` ENUM('0','1','2') NULL DEFAULT '0' COLLATE 'utf8mb3_general_ci',
    `sp` ENUM('0','1') NULL DEFAULT '0' COLLATE 'utf8mb3_general_ci',
    `so` ENUM('0','1') NULL DEFAULT '0' COLLATE 'utf8mb3_general_ci',
    `status` INT(11) NULL DEFAULT NULL COMMENT '2=tindakan;3=lab;4=obat;5=radiologi;6=racikan',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 COLLATE='utf8mb3_general_ci'; 